version: '3.8'

services:
  db:
    build:
      context: ./database  # Path to your custom Dockerfile directory
      dockerfile: Dockerfile  # Your custom Dockerfile
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend_container
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production  # Set the environment to production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
