name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
    - name: Create and Activate Conda Environment
      run: |
        conda env create -f environment.yml
        conda activate myenv
    - name: Run Tests
      run: |
        python -m unittest discover tests



